### ISSUE TITLE
Fix the Displaying of Tables

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-tools#39] opened 2021-01-12 08:12 UTC
Need to fix the displaying of tables as shown in [1].

<img width="1440" alt="Screenshot 2021-01-12 at 13 41 37" src="https://user-images.githubusercontent.com/11707273/104287065-ee72bd00-54db-11eb-9f39-c1e54ece0bd3.png">

[1] https://ballerina.io/swan-lake/learn/api-docs/ballerina/#/http/records/ClientConfiguration

**Comment by shehan360** [comment] 2021-01-12 08:25
This is a duplicate of this issue: https://github.com/ballerina-platform/ballerina-dev-tools/issues/34
Since the issue is fixed, closing this issue.

**Closed by shehan360** 2021-01-12 08:25 UTC
